<?php
// DATA CONTOH dengan bentuk sama seperti kolom database. Dipakai hanya jika Controller tidak mengirim variabel yang sama.
// Hapus file ini kalau semua halaman sudah dikirimi data dari Controller.
$lib=$lib??['nama'=>'Perpustakaan Politeknik Negeri Lhokseumawe','alamat'=>'Politeknik Negeri Lhokseumawe, Aceh','email'=>'perpustakaan@pnl.ac.id','telp'=>'-','maks_pinjam'=>3,'lama_pinjam'=>7,'denda_per_hari'=>1000];
$kategori=$kategori??[['id'=>1,'nama_kategori'=>'Ekonomi'],['id'=>2,'nama_kategori'=>'Teknologi'],['id'=>3,'nama_kategori'=>'Hukum'],['id'=>4,'nama_kategori'=>'Sastra'],['id'=>5,'nama_kategori'=>'Sains']];
$tipe_koleksi=$tipe_koleksi??[['id'=>1,'nama_tipe'=>'buku'],['id'=>2,'nama_tipe'=>'e-book'],['id'=>3,'nama_tipe'=>'e-jurnal'],['id'=>4,'nama_tipe'=>'e-TGA']];
$lokasi=$lokasi??[['id'=>1,'nama_ruang'=>'Rak A'],['id'=>2,'nama_ruang'=>'Rak B'],['id'=>3,'nama_ruang'=>'Ruang Referensi']];
$jenis_user=$jenis_user??[['id'=>1,'nama_role'=>'admin','deskripsi'=>'Akses penuh'],['id'=>2,'nama_role'=>'petugas','deskripsi'=>'Kelola koleksi dan peminjaman'],['id'=>3,'nama_role'=>'mahasiswa','deskripsi'=>'Anggota mahasiswa'],['id'=>4,'nama_role'=>'dosen','deskripsi'=>'Anggota dosen']];
$buku=$buku??[['id'=>1,'judul'=>'Manajemen Keuangan Modern','penulis'=>'Brigham Houston','penerbit'=>'Salemba Empat','tahun'=>2019,'isbn'=>'978-602-0001','stok'=>3,'kategori_id'=>1,'tipe_koleksi_id'=>1,'lokasi_id'=>1,'kategori'=>['id'=>1,'nama_kategori'=>'Ekonomi'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>1,'nama_ruang'=>'Rak A']],['id'=>2,'judul'=>'Dasar-dasar Basis Data','penulis'=>'Elmasri','penerbit'=>'Pearson','tahun'=>2016,'isbn'=>'978-602-0002','stok'=>5,'kategori_id'=>2,'tipe_koleksi_id'=>1,'lokasi_id'=>2,'kategori'=>['id'=>2,'nama_kategori'=>'Teknologi'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>2,'nama_ruang'=>'Rak B']],['id'=>3,'judul'=>'Pengantar Hukum Indonesia','penulis'=>'Soerjono Soekanto','penerbit'=>'Rajawali','tahun'=>2014,'isbn'=>'978-602-0003','stok'=>2,'kategori_id'=>3,'tipe_koleksi_id'=>1,'lokasi_id'=>1,'kategori'=>['id'=>3,'nama_kategori'=>'Hukum'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>1,'nama_ruang'=>'Rak A']],['id'=>4,'judul'=>'Laskar Pelangi','penulis'=>'Andrea Hirata','penerbit'=>'Bentang','tahun'=>2005,'isbn'=>'978-602-0004','stok'=>4,'kategori_id'=>4,'tipe_koleksi_id'=>1,'lokasi_id'=>2,'kategori'=>['id'=>4,'nama_kategori'=>'Sastra'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>2,'nama_ruang'=>'Rak B']],['id'=>5,'judul'=>'Ekonomi Makro','penulis'=>'Mankiw','penerbit'=>'Erlangga','tahun'=>2018,'isbn'=>'978-602-0005','stok'=>0,'kategori_id'=>1,'tipe_koleksi_id'=>1,'lokasi_id'=>1,'kategori'=>['id'=>1,'nama_kategori'=>'Ekonomi'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>1,'nama_ruang'=>'Rak A']],['id'=>6,'judul'=>'Pemrograman Web','penulis'=>'Budi Raharjo','penerbit'=>'Informatika','tahun'=>2020,'isbn'=>'978-602-0006','stok'=>6,'kategori_id'=>2,'tipe_koleksi_id'=>2,'lokasi_id'=>3,'kategori'=>['id'=>2,'nama_kategori'=>'Teknologi'],'tipe_koleksi'=>['id'=>2,'nama_tipe'=>'e-book'],'lokasi'=>['id'=>3,'nama_ruang'=>'Ruang Referensi']]];
$users=$users??[['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']],['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']]];
$peminjaman=$peminjaman??[['id'=>1,'user_id'=>3,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal_pinjam'=>'2026-09-25','tanggal_jatuh_tempo'=>'2026-10-02','tanggal_kembali'=>null,'status'=>'aktif','detail_peminjaman'=>[['jumlah'=>1,'denda'=>0,'buku'=>['judul'=>'Dasar-Dasar Basis Data']]],'petugas'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']]],['id'=>2,'user_id'=>2,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal_pinjam'=>'2026-09-20','tanggal_jatuh_tempo'=>'2026-09-27','tanggal_kembali'=>'2026-09-25','status'=>'dikembalikan','detail_peminjaman'=>[['jumlah'=>1,'denda'=>0,'buku'=>['judul'=>'Manajemen Keuangan Modern']]],'petugas'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']]],['id'=>3,'user_id'=>3,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal_pinjam'=>'2026-09-14','tanggal_jatuh_tempo'=>'2026-09-21','tanggal_kembali'=>null,'status'=>'terlambat','detail_peminjaman'=>[['jumlah'=>1,'denda'=>0,'buku'=>['judul'=>'Ekonomi Makro']]],'petugas'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']]],['id'=>4,'user_id'=>2,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal_pinjam'=>'2026-09-24','tanggal_jatuh_tempo'=>'2026-10-01','tanggal_kembali'=>null,'status'=>'pending','detail_peminjaman'=>[['jumlah'=>1,'denda'=>0,'buku'=>['judul'=>'Laskar Pelangi']]],'petugas'=>null]];
$absensi=$absensi??[['id'=>1,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal'=>'2026-09-25','waktu_masuk'=>'08:10','waktu_keluar'=>'11:30','metode'=>'qr'],['id'=>2,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'tanggal'=>'2026-09-25','waktu_masuk'=>'09:02','waktu_keluar'=>null,'metode'=>'manual']];
$feedback=$feedback??[['id'=>1,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'jenis'=>'saran','isi'=>'Tambah jam buka saat ujian','balasan'=>null,'status'=>'baru'],['id'=>2,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'jenis'=>'tanya_pustakawan','isi'=>'Bagaimana cara akses e-jurnal?','balasan'=>'Login lalu buka menu Library guides','status'=>'selesai']];
$event=$event??[['id'=>1,'judul'=>'Seminar Literasi Digital','deskripsi'=>'Seminar terbuka','tanggal_mulai'=>'2026-10-10','tanggal_selesai'=>'2026-10-10','lokasi'=>'Auditorium Perpustakaan','kuota'=>150,'peserta_count'=>150],['id'=>2,'judul'=>'Pelatihan Scopus','deskripsi'=>'Pelatihan pencarian jurnal','tanggal_mulai'=>'2026-10-22','tanggal_selesai'=>'2026-10-22','lokasi'=>'Area multimedia','kuota'=>40,'peserta_count'=>12]];
$artikel=$artikel??[['id'=>1,'judul'=>'Jam layanan diperpanjang saat ujian','kategori'=>'artikel','konten'=>'Layanan buka sampai 20.00 selama pekan ujian.','tanggal_terbit'=>'2026-09-20','penulis'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']]],['id'=>2,'judul'=>'Review: Laskar Pelangi','kategori'=>'book_review','konten'=>'Kisah persahabatan anak Belitung.','tanggal_terbit'=>'2026-09-18','penulis'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']]]];
$stat=$stat??['buku'=>12450,'anggota'=>3240,'dipinjam'=>560,'terlambat'=>32,'denda'=>2500000];
$koleksi=$koleksi??['tersedia'=>9338,'dipinjam'=>2490,'lain'=>622];
$grafik=$grafik??[['Sen',52],['Sel',58],['Rab',78],['Kam',70],['Jum',95],['Sab',64],['Min',50]];
$notif=$notif??[['danger','!','5 buku terlambat dikembalikan','2 jam yang lalu'],['warning','⏱','Aturan denda perlu ditinjau ulang','3 jam yang lalu'],['info','✎','3 feedback belum dijawab','5 jam yang lalu'],['success','＋','Pendaftaran anggota baru','1 hari yang lalu']];
$ejurnal=$ejurnal??[['id'=>1,'kategori_id'=>2,'kategori'=>['id'=>2,'nama_kategori'=>'Teknologi'],'judul'=>'Penerapan Machine Learning pada Perpustakaan Digital','penulis'=>'Rahmat Hidayat','abstrak'=>'Kajian penerapan pembelajaran mesin untuk rekomendasi koleksi di perpustakaan perguruan tinggi.','tahun'=>2024,'lokasi_rak'=>'Rak J-1'],['id'=>2,'kategori_id'=>1,'kategori'=>['id'=>1,'nama_kategori'=>'Ekonomi'],'judul'=>'Analisis Literasi Keuangan Mahasiswa Politeknik','penulis'=>'Nurul Aini','abstrak'=>'Penelitian tingkat literasi keuangan mahasiswa dan faktor yang memengaruhinya.','tahun'=>2023,'lokasi_rak'=>'Rak J-2']];
$reservasi=$reservasi??[['id'=>1,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'buku_id'=>5,'buku'=>['id'=>5,'judul'=>'Ekonomi Makro','penulis'=>'Mankiw','penerbit'=>'Erlangga','tahun'=>2018,'isbn'=>'978-602-0005','stok'=>0,'kategori_id'=>1,'tipe_koleksi_id'=>1,'lokasi_id'=>1,'kategori'=>['id'=>1,'nama_kategori'=>'Ekonomi'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>1,'nama_ruang'=>'Rak A']],'tanggal_reservasi'=>'2026-09-24','status'=>'menunggu'],['id'=>2,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'buku_id'=>3,'buku'=>['id'=>3,'judul'=>'Pengantar Hukum Indonesia','penulis'=>'Soerjono Soekanto','penerbit'=>'Rajawali','tahun'=>2014,'isbn'=>'978-602-0003','stok'=>2,'kategori_id'=>3,'tipe_koleksi_id'=>1,'lokasi_id'=>1,'kategori'=>['id'=>3,'nama_kategori'=>'Hukum'],'tipe_koleksi'=>['id'=>1,'nama_tipe'=>'buku'],'lokasi'=>['id'=>1,'nama_ruang'=>'Rak A']],'tanggal_reservasi'=>'2026-09-22','status'=>'tersedia']];
$tugas_akhir=$tugas_akhir??[['id'=>1,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'reviewer'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']],'judul'=>'Sistem Informasi Perpustakaan Berbasis Web','file_path'=>'ta/sip.pdf','status'=>'diajukan','catatan_reviewer'=>null],['id'=>2,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'reviewer'=>['id'=>1,'name'=>'Admin Perpustakaan','email'=>'admin@pnl.ac.id','nim_nip'=>'','jenis_user_id'=>1,'jenis_user'=>['nama_role'=>'admin']],'judul'=>'Rancang Bangun Aplikasi Absensi QR','file_path'=>'ta/absensi.pdf','status'=>'disetujui','catatan_reviewer'=>'Sudah sesuai pedoman']];
$event_peserta=$event_peserta??[['id'=>1,'event_id'=>1,'user'=>['id'=>2,'name'=>'Siti Nurhaliza','email'=>'siti@pnl.ac.id','nim_nip'=>'2203001','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'status_pendaftaran'=>'diterima','tanggal_daftar'=>'2026-09-20'],['id'=>2,'event_id'=>1,'user'=>['id'=>3,'name'=>'Andi Pratama','email'=>'andi@pnl.ac.id','nim_nip'=>'2203002','jenis_user_id'=>3,'jenis_user'=>['nama_role'=>'mahasiswa']],'status_pendaftaran'=>'menunggu','tanggal_daftar'=>'2026-09-21']];
$role=data_get(auth()->user(),'jenis_user.nama_role') ?? 'admin';   // sesuaikan dengan relasi model User tim
$isAdmin=in_array($role,['admin','petugas']);
$badge=function($s){$s=strtolower((string)$s);
 if(in_array($s,['aktif','hadir','diterima','tersedia','selesai','disetujui','sudah','qr']))return 'b-green';
 if(in_array($s,['terlambat','ditolak','dibatalkan']))return 'b-red';
 if(in_array($s,['pending','menunggu','baru','diajukan','diproses','belum']))return 'b-amber';
 return 'b-blue';};
$opt=fn($c,$v,$l)=>collect($c)->map(fn($x)=>[data_get($x,$v),data_get($x,$l)])->all();
$en=fn($a)=>array_map(fn($x)=>[$x,ucfirst(str_replace('_',' ',$x))],$a);
$f_buku=[['judul','Judul','text',12],['penulis','Penulis'],['penerbit','Penerbit'],['tahun','Tahun','number',3],['isbn','ISBN / kode','text',5],['stok','Stok','number',4],['kategori_id','Kategori','select',4,$opt($kategori,'id','nama_kategori')],['tipe_koleksi_id','Tipe koleksi','select',4,$opt($tipe_koleksi,'id','nama_tipe')],['lokasi_id','Lokasi','select',4,$opt($lokasi,'id','nama_ruang')],['cover','Cover','file',12]];
$f_user=[['name','Nama'],['email','Email','email'],['nim_nip','NIM / NIP'],['jenis_user_id','Jenis user','select',6,$opt($jenis_user,'id','nama_role')],['password','Password','password']];

$f_pinjam=[['buku_id','Buku','select',6,$opt($buku,'id','judul')],['jumlah','Jumlah','number',6],['tanggal_pinjam','Tanggal pinjam','date'],['tanggal_jatuh_tempo','Jatuh tempo','date']];
$f_resv=[['buku_id','Buku','select',8,$opt($buku,'id','judul')],['status','Status (petugas)','select',4,$en(['menunggu','tersedia','dibatalkan'])]];
$f_ej=[['judul','Judul','text',12],['penulis','Penulis'],['kategori_id','Kategori','select',3,$opt($kategori,'id','nama_kategori')],['tahun','Tahun','number',3],['lokasi_rak','Lokasi rak'],['abstrak','Abstrak','textarea',12]];
$f_ta=[['judul','Judul tugas akhir','text',12],['file_path','File (PDF)','file',12],['status','Status (reviewer)','select',6,$en(['diajukan','disetujui','ditolak'])],['catatan_reviewer','Catatan reviewer','textarea',12]];
$eventDetail=$eventDetail??$event[0];
